# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder # type: ignore
from google.protobuf import descriptor as _descriptor # type: ignore
from google.protobuf import descriptor_pool as _descriptor_pool # type: ignore
from google.protobuf import symbol_database as _symbol_database # type: ignore
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transaction.proto\x12\x0btransaction\"K\n\x15TransactionModelProto\x12\x10\n\x08stripeId\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\t\x12\x10\n\x08order_id\x18\x03 \x01(\t\"a\n\x10TransactionProto\x12<\n\x10TransactionModel\x18\x01 \x01(\x0b\x32\".transaction.TransactionModelProto\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSACTIONMODELPROTO._serialized_start=34
  _TRANSACTIONMODELPROTO._serialized_end=109
  _TRANSACTIONPROTO._serialized_start=111
  _TRANSACTIONPROTO._serialized_end=208
# @@protoc_insertion_point(module_scope)
