# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\"<\n\x0eSizeProtoModel\x12\x0c\n\x04size\x18\x01 \x01(\x05\x12\r\n\x05price\x18\x02 \x01(\x02\x12\r\n\x05stock\x18\x03 \x01(\x05\"q\n\x19ProductItemFormProtoModel\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12\x11\n\timage_url\x18\x03 \x01(\t\x12\x1e\n\x05sizes\x18\x04 \x03(\x0b\x32\x0f.SizeProtoModelb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIZEPROTOMODEL._serialized_start=19
  _SIZEPROTOMODEL._serialized_end=79
  _PRODUCTITEMFORMPROTOMODEL._serialized_start=81
  _PRODUCTITEMFORMPROTOMODEL._serialized_end=194
# @@protoc_insertion_point(module_scope)
