name: Deploy Service1

on:
  push:
    paths:
      - 'notification-services/**'
      - '.github/workflows/notification.yml'
      - 'main.bicep'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./service1
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/notification_service:latest

      - name: Deploy Bicep file
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./main.bicep
          parameters: |
            Image=${{ secrets.DOCKER_HUB_USERNAME }}/notification_service:latest
            ContainerAppName=abbasimart-notification_service-${{ github.run_id }}
          scope: resourcegroup
          failOnStdErr: false
